name: py311gs_surfel
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - plyfile
  - python
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - pymeshlab
    - opencv-python
    - matplotlib
    - imageio
    - scikit-image
    - numba
    - open3d
    - trimesh
    - "git+https://github.com/facebookresearch/pytorch3d.git"
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
